# Autor: David Fuertes
# github: dafuer



    
JpgraphBundle_graph_drawtimeseries:
    pattern:  /graph/drawtimeseries
    defaults: { _controller: DafuerJpgraphBundle:Default:drawtimeseries }
    options:
        expose: true
        

        
#JpgraphBundle_graph_query:
#    pattern:  /graph/imggraph
#    defaults: { _controller: DafuerJpgraphBundle:Default:imggraph }
 

        
JpgraphBundle_graph_viewdrawtimeseries:
    pattern:  /graph/viewdrawtimeseries
    defaults: { _controller: DafuerJpgraphBundle:Default:viewdrawtimeseries }

    
JpgraphBundle_graph_style_show:
    pattern:  /graph/style/{style_name}/show
    defaults: { _controller: DafuerJpgraphBundle:Default:styleshow }
    
JpgraphBundle_graph_viewer:
    pattern:  /graph/viewer/{insertgraphroute}
    defaults: { _controller: DafuerJpgraphBundle:Viewer:viewer }
   
  
    
JpgraphBundle_graph_insertgraph:
    pattern:  /graph/insertgraph/{form}/{combined}/{formgraphpath}
    defaults: { _controller: DafuerJpgraphBundle:Viewer:insertgraph }
    options:
        expose: true       

 
JpgraphBundle_graph_query:
    pattern:  /graph/query
    defaults: { _controller: DafuerJpgraphBundle:Default:query } 