
JpgraphBundle_graph_query:
    pattern:  /query
    defaults: { _controller: DafuerJpgraphBundle:Graph:query }
    options:
        expose: true   


JpgraphBundle_graph_stylequeryshow:
    pattern:  /query
    defaults: { _controller: DafuerJpgraphBundle:Graph:stylequeryshow }

JpgraphBundle_graph_imgerrordraw:
    pattern:  /graph/imgerrordraw/{style}
    defaults: { _controller: DafuerJpgraphBundle:Graph:imgerrordraw } 

JpgraphBundle_graph_imgerror:
    pattern:  /graph/imgerror/{style}
    defaults: { _controller: DafuerJpgraphBundle:Graph:imgerror } 
    
#JpgraphBundle_graph_drawtimeseries:
#    pattern:  /drawtimeseries
#    defaults: { _controller: DafuerJpgraphBundle:Graph:drawtimeseries }
#    options:
#        expose: true
#        
#JpgraphBundle_graph_viewdrawtimeseries:
#    pattern:  /viewdrawtimeseries
#    defaults: { _controller: DafuerJpgraphBundle:Graph:viewdrawtimeseries }