
JpgraphBundle_graph_query:
    pattern:  /query
    defaults: { _controller: DafuerJpgraphBundle:Graph:query }
    options:
        expose: true   


JpgraphBundle_graph_stylequeryshow:
    pattern:  /query
    defaults: { _controller: DafuerJpgraphBundle:Graph:stylequeryshow }
